### ISSUE TITLE
Error with package with a prerelease version ("Invalid Version: 2.1.0pre")

### ISSUE THREAD

**Issue by ljharb** [NullVoxPopuli/package-majors#15]
Try `knockout` - in the console, you'll see `Invalid Version: 2.1.0pre`.

The `data` is:
```json
[
    {
        "package": "knockout",
        "downloads": {
            "2.3.0": 633,
            "3.5.0": 2181,
            "3.4.1": 436,
            "3.1.0": 31,
            "2.1.0pre": 1,
            "3.0.0": 829,
            "3.2.0": 450,
            "3.4.0": 781,
            "3.5.0-beta": 10,
            "3.4.2": 5021,
            "2.2.1": 132,
            "3.3.0": 637,
            "3.5.1": 62666,
            "3.5.0-rc": 17,
            "2.1.0": 3
        }
    }
]
```

as you can see, `2.1.0pre` (which is an invalid version) has a download. I think the logic probably needs to be updated to skip over invalid versions in `groupByMajor`?

**Comment by NullVoxPopuli** [comment]
I think you're correct! 
Thanks for reporting!

**Comment by NullVoxPopuli** [comment]
I opened https://github.com/NullVoxPopuli/package-majors/pull/16 which will print a message to the console if a library maintainer wants to debug or somethin'

**Comment by ljharb** [comment]
Thanks, makes sense!
