### ISSUE TITLE
OG meta for website info and thumbnails

### ISSUE THREAD

**Issue by rajasegar** [NullVoxPopuli/package-majors#2]
Looks like there is no OpenGraph meta in the index.html because of which I didn't get any thumbnail or description while sharing in various other sites

**Comment by NullVoxPopuli** [comment]
Thanks for the report! Fixed!

![Screenshot_20231124-101457](https://github.com/NullVoxPopuli/package-majors/assets/199018/23d16db0-c356-4c4a-b5fa-0a0593d53002)
