### ISSUE TITLE
chrome: Labels difficult to read in dark mode

### ISSUE THREAD

**Issue by marvinhagemeister** [NullVoxPopuli/package-majors#5]
Best explained via a screenshot.

<img width="633" alt="Screenshot 2023-11-24 at 10 46 16" src="https://github.com/NullVoxPopuli/package-majors/assets/1062408/783746cf-b57d-42c1-9288-1681fc71406d">

**Comment by NullVoxPopuli** [comment]
Fixed, thanks!

**Comment by NullVoxPopuli** [comment]
Reopening because i just found a ton of ui issues in mobile chrome

**Comment by NullVoxPopuli** [comment]
Looks like this'll be fixed in chrome 120:

![Screenshot_20231124-100738](https://github.com/NullVoxPopuli/package-majors/assets/199018/9a92c00f-e9c5-4dcf-ad2f-236a440bf95d)

**Comment by webpro** [comment]
In Chrome v120 the toggles look better, but the labels are still hard to read:

<img width="527" alt="Screenshot 2023-12-11 at 9 10 44 AM" src="https://github.com/NullVoxPopuli/package-majors/assets/456426/ddacc110-b348-4197-a61c-fbef082357ca">

**Comment by NullVoxPopuli** [comment]
Doen your copy of Firefox have the same issues?

**Comment by webpro** [comment]
No, FF v120 is fine

**Comment by NullVoxPopuli** [comment]
Fixed chrome! it turns out that the combo of Chart.JS + Chrome doesn't work with using `currentColor` as the axis/tick/label colors.
